/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zapateriasistema;


import java.awt.Color;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;




/**
 *
 * @author DELL
 */
public class clientes extends javax.swing.JFrame {
    conexion cn = new conexion();
    TableRowSorter trs;
    
    /**
     * Creates new form clientes
     */
    public clientes() {
        this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
        cargarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        textname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textprecio = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        label = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        txtcant = new javax.swing.JTextField();
        txtfecha = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtbuscar = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(903, 493));

        jPanel1.setBackground(new java.awt.Color(111, 37, 37));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Registrar Producto");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 230, 40));

        txtcodigo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtcodigo.setBorder(null);
        txtcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttxtcodigoActionPerformed(evt);
            }
        });
        jPanel2.add(txtcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 220, 30));

        jPanel3.setBackground(new java.awt.Color(255, 204, 51));
        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 220, 2));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Codigo");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 50, 40));

        jPanel4.setBackground(new java.awt.Color(255, 204, 51));
        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 220, 2));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Nombre");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        textname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textname.setBorder(null);
        textname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttextnameActionPerformed(evt);
            }
        });
        jPanel2.add(textname, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 220, 30));
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 50, 40));

        textprecio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textprecio.setBorder(null);
        textprecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttextprecioActionPerformed(evt);
            }
        });
        jPanel2.add(textprecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 220, 30));

        jPanel5.setBackground(new java.awt.Color(255, 204, 51));
        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 220, 2));
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 50, 40));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("Precio Unitario");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        jPanel6.setBackground(new java.awt.Color(255, 204, 51));
        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 220, 2));

        label.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label.setText("Cantidad");
        jPanel2.add(label, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 50, 40));

        label1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label1.setText("Fecha de ingreso");
        jPanel2.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, -1, -1));

        txtcant.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtcant.setBorder(null);
        txtcant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttxtcantActionPerformed(evt);
            }
        });
        jPanel2.add(txtcant, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 220, 30));

        txtfecha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfecha.setBorder(null);
        txtfecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttxtfechaActionPerformed(evt);
            }
        });
        jPanel2.add(txtfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 220, 30));

        jPanel8.setBackground(new java.awt.Color(255, 204, 51));
        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 220, 2));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 330, 440));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla.setGridColor(new java.awt.Color(204, 204, 204));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 500, 190));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC\\Downloads\\Nueva carpeta (2)\\disco-flexible (2).png")); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 80, 90));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Guardar");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, -1, -1));

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("x");
        jButton2.setBorder(null);
        jButton2.setMargin(new java.awt.Insets(1, 10, 2, 10));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 10, 40, 30));

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC\\Downloads\\Nueva carpeta (2)\\actualizar.png")); // NOI18N
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, 80, 90));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Actualizar");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 110, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC\\Downloads\\Nueva carpeta (2)\\borrar.png")); // NOI18N
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 20, 80, 90));

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Eliminar");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 110, -1, -1));

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Buscar");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 170, -1, -1));

        txtbuscar.setBackground(new java.awt.Color(111, 37, 37));
        txtbuscar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtbuscar.setForeground(new java.awt.Color(255, 255, 255));
        txtbuscar.setBorder(null);
        txtbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttxtbuscarActionPerformed(evt);
            }
        });
        txtbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtbuscarKeyTyped(evt);
            }
        });
        jPanel1.add(txtbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, 220, 30));

        jPanel7.setBackground(new java.awt.Color(255, 204, 51));
        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 220, 220, 2));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC\\Downloads\\Nueva carpeta (2)\\buscar.png")); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, 40, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 964, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txttxtcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttxtcodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttxtcodigoActionPerformed

    private void txttextnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttextnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttextnameActionPerformed

    private void txttextprecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttextprecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttextprecioActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Inicio regresar = new Inicio();
        regresar.show();
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txttxtbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttxtbuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttxtbuscarActionPerformed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        insertarDatos();
        limpiar();
        cargarDatos();
    }//GEN-LAST:event_jLabel10MouseClicked

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        // TODO add your handling code here:
        int rowSelect = tabla.rowAtPoint(evt.getPoint());
        txtcodigo.setText(tabla.getValueAt(rowSelect,0).toString());
        textname.setText(tabla.getValueAt(rowSelect,1).toString());
        textprecio.setText(tabla.getValueAt(rowSelect,2).toString());
        txtcant.setText(tabla.getValueAt(rowSelect,3).toString());
        txtfecha.setText(tabla.getValueAt(rowSelect,4).toString());
    }//GEN-LAST:event_tablaMouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        actualizarDatos();
        limpiar();
        cargarDatos();
        
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
        eliminarDatos();
        limpiar();
        cargarDatos();
    }//GEN-LAST:event_jLabel14MouseClicked

    private void txtbuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyTyped
        // TODO add your handling code here:
        txtbuscar.addKeyListener(new KeyAdapter(){
            @Override
            public void keyReleased(KeyEvent ke){
                trs.setRowFilter(RowFilter.regexFilter("(?i)"+txtbuscar.getText(), 0,1,2));    
            }
        });
        trs = new TableRowSorter(tabla.getModel());
        tabla.setRowSorter(trs); 
    }//GEN-LAST:event_txtbuscarKeyTyped

    private void txttxtcantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttxtcantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttxtcantActionPerformed

    private void txttxtfechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttxtfechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttxtfechaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new clientes().setVisible(true);
            }
        });
    }
    
    public void insertarDatos (){
        try {
            String Query = "Insert into producto (codigoProducto,nombreProducto,precioUnitario,cantidadProducto,fechaVencimiento) values "
                    + "(?,?,?,?,?)";
            PreparedStatement ps = cn.con.prepareStatement(Query);
            ps.setString(1, txtcodigo.getText());
            ps.setString(2, textname.getText());
            ps.setString(3, textprecio.getText());
            ps.setString(4, txtcant.getText());
            ps.setString(5, txtfecha.getText());
            ps.execute();
            System.out.println("Datos Guardados correctamente.");
            JOptionPane.showMessageDialog(null, "Datos guardados correctamente.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No se pudieron guardar los datos."+ e.getMessage());
            
        }
    }
    
    public void limpiar(){
        txtcodigo.setText("");
        textname.setText("");
        textprecio.setText("");
        txtcant.setText("");
        txtfecha.setText("");
    }
    
    public void cargarDatos(){
        String[] encabezado = {"Codigo","Producto","Precio","Cantidad","Fecha Ingreso"};
        String [] contRegistro = new String[10];
        DefaultTableModel modelo = new DefaultTableModel(null,encabezado);
        String Query = "select * from producto";
        try {
            Statement st = cn.con.createStatement();
            ResultSet rs = st.executeQuery(Query);
            while(rs.next()){
                contRegistro[0] = rs.getString("codigoProducto");
                contRegistro[1] = rs.getString("nombreProducto");
                contRegistro[2] = rs.getString("precioUnitario");
                contRegistro[3] = rs.getString("cantidadProducto");
                contRegistro[4] = rs.getString("fechaVencimiento");
                modelo.addRow(contRegistro);
            }
            tabla.setModel(modelo);
            
        } catch (Exception e) {
            System.out.println("ERROR, datos no cargados "+ e.getMessage());
            
            
        }
    }
    
    public void actualizarDatos(){
        try {
            String Query = "update producto set codigoProducto=?, nombreProducto=?, precioUnitario=?, cantidadProducto=?, fechaVencimiento=? where codigoProducto=?";
            
            PreparedStatement ps = cn.con.prepareStatement(Query);
            int rowSelect = tabla.getSelectedRow();
            String date = (String)tabla.getValueAt(rowSelect,0);
            ps.setString(1, txtcodigo.getText());
            ps.setString(2, textname.getText());
            ps.setString(3, textprecio.getText());
            ps.setString(4, txtcant.getText());
            ps.setString(5, txtfecha.getText());
            ps.setString(6,date);
            ps.execute();
            System.out.println("Datos actualizados");
            JOptionPane.showMessageDialog(null, "Datos actualizados correctamente.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERROR, no se actualizaron los datos."+ e.getMessage());
            
        }
    }
    
     public void eliminarDatos(){
        int rowSelect = tabla.getSelectedRow();
        try {
            String Query = "delete from producto where codigoProducto="+tabla.getValueAt(rowSelect, 0);
            Statement st = cn.con.createStatement();
            int num = st.executeUpdate(Query);
            if(num>=0){
                System.out.println("Se eliminaron los datos.");
                JOptionPane.showMessageDialog(null,"Datos eliminados correctamente");
            }
        } catch (Exception e) {
            System.out.println("ERROR, al eliminar los datos.");
                JOptionPane.showMessageDialog(null,"ERROR, no se pudieron eliminar."+e.getMessage());
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label;
    private javax.swing.JLabel label1;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField textname;
    private javax.swing.JTextField textprecio;
    private javax.swing.JTextField txtbuscar;
    private javax.swing.JTextField txtcant;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtfecha;
    // End of variables declaration//GEN-END:variables
}
