
package zapateriasistema;

import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;



public class InicioLogin extends javax.swing.JFrame {
    
    conexion cn = new conexion();
    private boolean usuarioAdmin = false;
    private boolean usuarioNormal = false;
    

    /**
     * Creates new form InicioLogin
     */
    public InicioLogin() {
        this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtusuario = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        contra = new javax.swing.JPasswordField();
        jPanel4 = new javax.swing.JPanel();
        iniciar = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        iniciar1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("AUTO REPUESTOS");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 180, 40));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Usuario");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        txtusuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtusuario.setBorder(null);
        txtusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttxtusuarioActionPerformed(evt);
            }
        });
        jPanel2.add(txtusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 220, 30));

        jPanel3.setBackground(new java.awt.Color(255, 204, 51));
        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 220, 2));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Contraseña");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        contra.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        contra.setBorder(null);
        jPanel2.add(contra, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 220, 30));

        jPanel4.setBackground(new java.awt.Color(255, 204, 51));
        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 220, 2));

        iniciar.setBackground(new java.awt.Color(111, 37, 37));
        iniciar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                iniciarMouseMoved(evt);
            }
        });
        iniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iniciarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                iniciarMouseExited(evt);
            }
        });
        iniciar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("INICIAR");
        iniciar.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 90, 20));

        jPanel2.add(iniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 110, 40));

        iniciar1.setBackground(new java.awt.Color(111, 37, 37));
        iniciar1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                iniciar1MouseMoved(evt);
            }
        });
        iniciar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iniciar1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                iniciar1MouseExited(evt);
            }
        });
        iniciar1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("REGISTRARSE");
        iniciar1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 20));

        jPanel2.add(iniciar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 110, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 310, 360));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 450));

        jPanel1.setBackground(new java.awt.Color(111, 37, 37));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("x");
        jButton2.setBorder(null);
        jButton2.setMargin(new java.awt.Insets(1, 10, 2, 10));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 40, 30));

        jButton1.setBackground(new java.awt.Color(255, 204, 0));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("-");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 40, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 310, 450));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setExtendedState(ICONIFIED);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void txttxtusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttxtusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttxtusuarioActionPerformed

    private void iniciarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iniciarMouseMoved
        // TODO add your handling code here:
        iniciar.setBackground(new Color(66,20,20));

    }//GEN-LAST:event_iniciarMouseMoved

    private void iniciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iniciarMouseClicked
        // TODO add your handling code here:
        verificarUsuario();
        if(usuarioAdmin){
            JOptionPane.showMessageDialog(null, "se inicio la sesion correctamente", "¡Bienvenido administrador!", JOptionPane.INFORMATION_MESSAGE);
            new Inicio().setVisible(true);
            setVisible(false);
            LimpiarDatos();  
        }else if(usuarioNormal){
            JOptionPane.showMessageDialog(null, "se inicio la sesion correctamente", "¡Bienvenido usuario!", JOptionPane.INFORMATION_MESSAGE);
            new Inicio().setVisible(true);
            setVisible(false);
            LimpiarDatos();
        }else{
            JOptionPane.showMessageDialog(null,"Usuario no identificado","¡ERROR!",JOptionPane.ERROR_MESSAGE);
            System.out.println("Usuario no identificado");
            LimpiarDatos();
        }
        
        
    }//GEN-LAST:event_iniciarMouseClicked

    private void iniciarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iniciarMouseExited
        // TODO add your handling code here:
        iniciar.setBackground(new Color(111,37,37));
    }//GEN-LAST:event_iniciarMouseExited

    private void iniciar1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iniciar1MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_iniciar1MouseMoved

    private void iniciar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iniciar1MouseClicked
        // TODO add your handling code here:
        registro registro = new registro();
        registro.show();
        dispose();
                  
        
    }//GEN-LAST:event_iniciar1MouseClicked

    private void iniciar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iniciar1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_iniciar1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioLogin().setVisible(true);
            }
        });
    }
    
    public void verificarUsuario(){
        try {
            String user = "admin";
            
            Statement st = cn.con.createStatement();
            ResultSet Rs = st.executeQuery("select nombre,usuario, pass from usuarios where usuario='"+txtusuario.getText()+"'");
            while(Rs.next()){
                if(contra.getText().equals(Rs.getString("pass")) && user.equalsIgnoreCase(Rs.getString("usuario"))){
                    usuarioAdmin = true;
                }
                usuarioNormal = true;
            }
        } catch (Exception e) {
            System.out.println("¡ERROR!"+e.getMessage());
        }
    }
    
    public void LimpiarDatos(){
        txtusuario.setText("");
        contra.setText("");
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField contra;
    private javax.swing.JPanel iniciar;
    private javax.swing.JPanel iniciar1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
}
